In [81]:
# Name - Karthik Ragunath Ananda Kumar
# Net ID - KXA200005

In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [2]:
cd 'drive/MyDrive/HW1'

/content/drive/MyDrive/HW1


In [56]:
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from cvxopt import matrix, solvers
from numpy import linalg as LA

In [72]:
# Utility Function To Check Convergence

In [5]:
def check_convergence(W, X, b, Y, M):
  check_classifications = np.multiply(Y, np.add(np.sum(np.multiply(W, X), axis = 1).reshape(-1, 1), b)).reshape(M,)
  valid = 0
  for i in range(M):
    if check_classifications[i] > 0:
      valid += 1
  if valid == M:
    return True
  else:
    return False

In [78]:
# *********************************************************

In [62]:
# Problem 1

In [4]:
perceptron_df = pd.read_csv('perceptron.data', names=["x1", "x2", "x3", "x4", "y"], header=None)
W = np.array([0, 0, 0, 0])
b = 0
M = len(perceptron_df)
X = perceptron_df[['x1', 'x2', 'x3', 'x4']].to_numpy()
Y = perceptron_df[['y']].to_numpy()

In [7]:
## Printing Weights And Biases For FIrst 3 Epochs

In [73]:
## Problem 1.2.b.(i)

In [64]:
## Standard Sub-Gradient Descent

In [20]:
X = perceptron_df[['x1', 'x2', 'x3', 'x4']].to_numpy()
Y = perceptron_df[['y']].to_numpy()
Y = Y.reshape(-1,1)
step_size = 1
num_epochs = 0
M = len(perceptron_df)
W = np.array([0.0, 0.0, 0.0, 0.0])
b = 0
while True:
  # loss = (max{0, (1 - y(wx + b))})^2
  WX = np.sum(np.multiply(W, X), axis=1) # 999 * 1
  linear_sum = WX + b # 999 * 1
  y_linear_sum_mult = np.multiply(Y, linear_sum.reshape(-1, 1)) # 999 * 1
  y_linear_sum_mult = (1 - y_linear_sum_mult) # 999 * 1
  perceptron_loss = np.maximum(y_linear_sum_mult, 0) ** 2 ### 999 * 1
  perceptron_loss = (1 / M) * np.sum(perceptron_loss) # scalar
  pre_compute = np.multiply(2, np.maximum(0, y_linear_sum_mult))
  w1_grad = np.sum(np.multiply(pre_compute, np.multiply(-1, np.multiply(Y, X[:, 0].reshape(-1, 1))))) / M 
  w2_grad = np.sum(np.multiply(pre_compute, np.multiply(-1, np.multiply(Y, X[:, 1].reshape(-1, 1))))) / M
  w3_grad = np.sum(np.multiply(pre_compute, np.multiply(-1, np.multiply(Y, X[:, 2].reshape(-1, 1))))) / M 
  w4_grad = np.sum(np.multiply(pre_compute, np.multiply(-1, np.multiply(Y, X[:, 3].reshape(-1, 1))))) / M 
  b_grad = np.sum(np.multiply(pre_compute, np.multiply(-1, Y))) / M
  W = np.subtract(W, np.multiply(step_size, np.array([w1_grad, w2_grad, w3_grad, w4_grad])))
  b = float(b) - (step_size * b_grad)
  print(W, b)
  num_epochs += 1
  if check_convergence(W, X, b, Y, M):
    print("Converges at:", num_epochs)
    break
  if num_epochs == 3:
    break

[ 2.5593007   0.91720162 -0.21666124 -3.34649272] -0.7107107107107107
[ 3.10103662  0.75017449  0.74855952 -1.74133898] -1.7639367134712167
[-1.27894356  0.66686132 -1.7713963  -5.280284  ] -2.9582693127116153


In [10]:
## Looking For Convergence With Step Size Of 1 and to get Final Weights and Biases [Using check_convergence utility function we wrote]

In [16]:
X = perceptron_df[['x1', 'x2', 'x3', 'x4']].to_numpy()
Y = perceptron_df[['y']].to_numpy()
Y = Y.reshape(-1,1)
step_size = 1
num_epochs = 0
M = len(perceptron_df)
W = np.array([0.0, 0.0, 0.0, 0.0])
b = 0
while True:
  # loss = (max{0, (1 - y(wx + b))})^2
  WX = np.sum(np.multiply(W, X), axis=1) # 999 * 1
  linear_sum = WX + b # 999 * 1
  y_linear_sum_mult = np.multiply(Y, linear_sum.reshape(-1, 1)) # 999 * 1
  y_linear_sum_mult = (1 - y_linear_sum_mult) # 999 * 1
  perceptron_loss = np.maximum(y_linear_sum_mult, 0) ** 2 ### 999 * 1
  perceptron_loss = (1 / M) * np.sum(perceptron_loss) # scalar
  pre_compute = np.multiply(2, np.maximum(0, y_linear_sum_mult))
  w1_grad = np.sum(np.multiply(pre_compute, np.multiply(-1, np.multiply(Y, X[:, 0].reshape(-1, 1))))) / M 
  w2_grad = np.sum(np.multiply(pre_compute, np.multiply(-1, np.multiply(Y, X[:, 1].reshape(-1, 1))))) / M
  w3_grad = np.sum(np.multiply(pre_compute, np.multiply(-1, np.multiply(Y, X[:, 2].reshape(-1, 1))))) / M 
  w4_grad = np.sum(np.multiply(pre_compute, np.multiply(-1, np.multiply(Y, X[:, 3].reshape(-1, 1))))) / M 
  b_grad = np.sum(np.multiply(pre_compute, np.multiply(-1, Y))) / M
  W = np.subtract(W, np.multiply(step_size, np.array([w1_grad, w2_grad, w3_grad, w4_grad])))
  b = float(b) - (step_size * b_grad)
  print(W, b)
  num_epochs += 1
  if check_convergence(W, X, b, Y, M):
    print("Converges at:", num_epochs)
    break

[ 2.5593007   0.91720162 -0.21666124 -3.34649272] -0.7107107107107107
[ 3.10103662  0.75017449  0.74855952 -1.74133898] -1.7639367134712167
[-1.27894356  0.66686132 -1.7713963  -5.280284  ] -2.9582693127116153
[19.39423156  3.48436074  6.44827186  8.02106584] -6.430339343178497
[ -66.9275766     5.42717096  -33.7133139  -125.46425744] -23.80650390713508
[687.17474981 150.43926486 151.62140964 288.8700515 ] -154.93199164521457
[-2417.57479971    29.20319906  -769.05057285 -4364.00915836] -816.5236847230977
[24428.58939209  6122.6854983   3247.59515245 10503.28472873] -5424.352630711846
[ -86205.8682843    -3268.80629528  -15776.21301218 -156170.66278193] -29020.596142757415
[872424.15451343 241769.41528274  54439.50861233 383578.31738554] -193637.17612192608
[-3078177.92382703  -243785.34000937  -238081.25419894 -5646208.24520851] -1037714.2819022202
[31393172.91572247  9402341.09271188   203794.83218494 13986893.63953592] -6971399.984087096
[-1.10306652e+08 -1.27606364e+07  9.77770444e

/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py:87: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:16: RuntimeWarning: overflow encountered in square
  app.launch_new_instance()


[-6.02236117e+159 -1.77895499e+159  1.89807214e+159 -1.21412410e+160] -2.1806618398296988e+159
[ 6.62018277e+160  2.66426763e+160 -1.23576416e+160  2.98122816e+160] -1.4830310586647978e+160
[-2.21069657e+161 -6.53021230e+160  6.96746914e+160 -4.45682334e+161] -8.004803282364196e+160
[ 2.43014574e+162  9.78003004e+161 -4.53625997e+161  1.09435331e+162] -5.443930677108162e+161
[-8.11505517e+162 -2.39711926e+162  2.55762809e+162 -1.63601680e+163] -2.9384141281782956e+162
[ 8.92061219e+163  3.59006679e+163 -1.66517651e+163  4.01716707e+163] -1.9983655125767596e+163
[-2.97888554e+164 -8.79937812e+163  9.38857616e+163 -6.00551284e+164] -1.078637073780494e+164
[ 3.27459051e+165  1.31784662e+165 -6.11255268e+164  1.47462718e+165] -7.335627433039833e+164
[-1.09349338e+166 -3.23008775e+165  3.44637137e+165 -2.20451186e+166] -3.959475710985117e+165
[ 1.20204116e+167  4.83756940e+166 -2.24380419e+166  5.41308160e+166] -2.692772142918955e+166
[-4.01401043e+167 -1.18570502e+167  1.26509871e+167 -8.0

/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py:87: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan nan nan] nan
[nan nan n

KeyboardInterrupt: ignored

In [26]:
## Standard Sub-Gradient Descent Not Converging For Step Size Of 1
## Final Weights and Biases - [nan nan nan nan] [nan]

In [74]:
## Problem 1.2.b.(ii)

In [17]:
## Stochastic Sub-Gradient Descent

In [18]:
## Getting Weights And Biases For First 3 Epochs

In [21]:
X = perceptron_df[['x1', 'x2', 'x3', 'x4']].to_numpy()
Y = perceptron_df[['y']].to_numpy()
Y = Y.reshape(-1,1)
step_size = 1
num_epochs = 0
M = len(perceptron_df)
W = np.array([0.0, 0.0, 0.0, 0.0])
b = 0
valid_break = False
while True:
  for index in range(M):
    WX = np.sum(np.multiply(W, X[index, :]))
    linear_sum = WX + b
    y_linear_sum_mult = Y[index] * linear_sum
    y_linear_sum_mult = (1 - y_linear_sum_mult)
    perceptron_loss = float(np.maximum(y_linear_sum_mult, 0) ** 2)
    w1_grad = (2 * np.maximum(0, (y_linear_sum_mult)) * -1 * Y[index] * X[index, 0])
    w2_grad = (2 * np.maximum(0, (y_linear_sum_mult)) * -1 * Y[index] * X[index, 1])
    w3_grad = (2 * np.maximum(0, (y_linear_sum_mult)) * -1 * Y[index] * X[index, 2])
    w4_grad = (2 * np.maximum(0, (y_linear_sum_mult)) * -1 * Y[index] * X[index, 3])
    b_grad = (2 * np.maximum(0, (y_linear_sum_mult)) * -1 * Y[index])
    W[0] = float(float(W[0]) - (float(step_size) * float(w1_grad)))
    W[1] = float(W[1]) - (float(step_size) * float(w2_grad))
    W[2] = float(W[2]) - (float(step_size) * float(w3_grad))
    W[3] = float(W[3]) - (float(step_size) * float(w4_grad))
    b = float(b) - (step_size * b_grad)
    print(W, b)
    num_epochs += 1
    valid_break = False
    if check_convergence(W, X, b, Y, M):
      print("Converges at:", num_epochs)
      valid_break = True
      break
    if num_epochs == 3:
      valid_break = True
      break
  if valid_break:
    break

[ 9.23508847  4.93935876  3.93532157 -3.62671101] [-2.]
[ 9.23508847  4.93935876  3.93532157 -3.62671101] [-2.]
[ -9.94935776 -32.96161921  14.81595005 -50.31810755] [-18.47693406]


In [25]:
X = perceptron_df[['x1', 'x2', 'x3', 'x4']].to_numpy()
Y = perceptron_df[['y']].to_numpy()
Y = Y.reshape(-1,1)
step_size = 1
num_epochs = 0
M = len(perceptron_df)
W = np.array([0.0, 0.0, 0.0, 0.0])
b = 0
valid_break = False
while True:
  for index in range(M):
    WX = np.sum(np.multiply(W, X[index, :]))
    linear_sum = WX + b
    y_linear_sum_mult = Y[index] * linear_sum
    y_linear_sum_mult = (1 - y_linear_sum_mult)
    perceptron_loss = float(np.maximum(y_linear_sum_mult, 0) ** 2)
    w1_grad = (2 * np.maximum(0, (y_linear_sum_mult)) * -1 * Y[index] * X[index, 0])
    w2_grad = (2 * np.maximum(0, (y_linear_sum_mult)) * -1 * Y[index] * X[index, 1])
    w3_grad = (2 * np.maximum(0, (y_linear_sum_mult)) * -1 * Y[index] * X[index, 2])
    w4_grad = (2 * np.maximum(0, (y_linear_sum_mult)) * -1 * Y[index] * X[index, 3])
    b_grad = (2 * np.maximum(0, (y_linear_sum_mult)) * -1 * Y[index])
    W[0] = float(float(W[0]) - (float(step_size) * float(w1_grad)))
    W[1] = float(W[1]) - (float(step_size) * float(w2_grad))
    W[2] = float(W[2]) - (float(step_size) * float(w3_grad))
    W[3] = float(W[3]) - (float(step_size) * float(w4_grad))
    b = float(b) - (step_size * b_grad)
    print(W, b)
    num_epochs += 1
    valid_break = False
    if check_convergence(W, X, b, Y, M):
      print("Converges at:", num_epochs)
      valid_break = True
      break
  if valid_break:
    break

[ 9.23508847  4.93935876  3.93532157 -3.62671101] [-2.]
[ 9.23508847  4.93935876  3.93532157 -3.62671101] [-2.]
[ -9.94935776 -32.96161921  14.81595005 -50.31810755] [-18.47693406]
[ 746.16377764 1053.68603662 -487.60666219  -59.4479095 ] [-318.73480113]
[ 746.16377764 1053.68603662 -487.60666219  -59.4479095 ] [-318.73480113]
[ 746.16377764 1053.68603662 -487.60666219  -59.4479095 ] [-318.73480113]
[ 746.16377764 1053.68603662 -487.60666219  -59.4479095 ] [-318.73480113]
[ 746.16377764 1053.68603662 -487.60666219  -59.4479095 ] [-318.73480113]
[-33769.58946305  -8336.55510793  25644.29735541 -37901.43145622] [-9612.62964166]
[ 404550.7726115   -32933.24767502 -981503.64942483 -375776.80822637] [235223.01822816]
[ 404550.7726115   -32933.24767502 -981503.64942483 -375776.80822637] [235223.01822816]
[ 404550.7726115   -32933.24767502 -981503.64942483 -375776.80822637] [235223.01822816]
[ 404550.7726115   -32933.24767502 -981503.64942483 -375776.80822637] [235223.01822816]
[ 5953411.7952

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:16: RuntimeWarning: overflow encountered in square
  app.launch_new_instance()


[ 1.72988367e+170  1.93432967e+170 -1.95687711e+170  1.22877930e+170] [-5.88571058e+169]
[1.74928201e+169 5.38208688e+170 1.37932060e+171 5.87682445e+170] [-6.52741241e+170]
[1.74928201e+169 5.38208688e+170 1.37932060e+171 5.87682445e+170] [-6.52741241e+170]
[ 4.44280267e+172 -1.13121239e+172 -7.52912832e+172 -3.76447190e+172] [-1.6372903e+172]
[ 4.44280267e+172 -1.13121239e+172 -7.52912832e+172 -3.76447190e+172] [-1.6372903e+172]
[ 4.44280267e+172 -1.13121239e+172 -7.52912832e+172 -3.76447190e+172] [-1.6372903e+172]
[ 4.44280267e+172 -1.13121239e+172 -7.52912832e+172 -3.76447190e+172] [-1.6372903e+172]
[ 4.44280267e+172 -1.13121239e+172 -7.52912832e+172 -3.76447190e+172] [-1.6372903e+172]
[ 4.44280267e+172 -1.13121239e+172 -7.52912832e+172 -3.76447190e+172] [-1.6372903e+172]
[ 4.44280267e+172 -1.13121239e+172 -7.52912832e+172 -3.76447190e+172] [-1.6372903e+172]
[ 4.44280267e+172 -1.13121239e+172 -7.52912832e+172 -3.76447190e+172] [-1.6372903e+172]
[ 4.44280267e+172 -1.13121239e+172 -7

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:17: RuntimeWarning: overflow encountered in multiply
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:20: RuntimeWarning: overflow encountered in multiply
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in multiply
  
/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py:87: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: RuntimeWarning: overflow encountered in multiply
  if sys.path[0] == '':


[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan] [nan]
[nan nan nan nan

KeyboardInterrupt: ignored

In [24]:
## Stochastic Sub-Gradient Descent Not Converging For Step Size Of 1
## Final Weights and Biases - [nan nan nan nan] [nan]

In [75]:
## Problem 1.2.b.(iii)

In [76]:
## Checking Convergence For Varying Step Sizes

In [27]:
def varying_step_sizes(step_size = 1):
  X = perceptron_df[['x1', 'x2', 'x3', 'x4']].to_numpy()
  Y = perceptron_df[['y']].to_numpy()
  Y = Y.reshape(-1,1)
  num_epochs = 0
  M = len(perceptron_df)
  W = np.array([0.0, 0.0, 0.0, 0.0])
  b = 0
  while True:
    WX = np.sum(np.multiply(W, X), axis=1)
    linear_sum = WX + b
    y_linear_sum_mult = np.multiply(Y, linear_sum.reshape(-1, 1))
    y_linear_sum_mult = (1 - y_linear_sum_mult)
    perceptron_loss = np.maximum(y_linear_sum_mult, 0) ** 2
    perceptron_loss = (1 / M) * np.sum(perceptron_loss)
    pre_compute = np.multiply(2, np.maximum(0, y_linear_sum_mult))
    w1_grad = np.sum(np.multiply(pre_compute, np.multiply(-1, np.multiply(Y, X[:, 0].reshape(-1, 1))))) / M 
    w2_grad = np.sum(np.multiply(pre_compute, np.multiply(-1, np.multiply(Y, X[:, 1].reshape(-1, 1))))) / M
    w3_grad = np.sum(np.multiply(pre_compute, np.multiply(-1, np.multiply(Y, X[:, 2].reshape(-1, 1))))) / M 
    w4_grad = np.sum(np.multiply(pre_compute, np.multiply(-1, np.multiply(Y, X[:, 3].reshape(-1, 1))))) / M 
    b_grad = np.sum(np.multiply(pre_compute, np.multiply(-1, Y))) / M
    W = np.subtract(W, np.multiply(step_size, np.array([w1_grad, w2_grad, w3_grad, w4_grad])))
    b = float(b) - (step_size * b_grad)
    num_epochs += 1
    if check_convergence(W, X, b, Y, M):
      print("Coverges at:", num_epochs)
      break

In [28]:
varying_step_sizes(step_size=0.001)

Coverges at: 368975


In [29]:
varying_step_sizes(step_size=0.0005)

Coverges at: 737952


In [61]:
varying_step_sizes(step_size=0.01)

Coverges at: 36895


In [77]:
## Checking Convergence For Varying Step Sizes In Stochastic Sub-Gradient Descent

In [33]:
def varying_step_sizes_stochastic(step_size=1):
  X = perceptron_df[['x1', 'x2', 'x3', 'x4']].to_numpy()
  Y = perceptron_df[['y']].to_numpy()
  Y = Y.reshape(-1,1)
  num_epochs = 0
  M = len(perceptron_df)
  W = np.array([0.0, 0.0, 0.0, 0.0])
  b = 0
  valid_break = False
  while True:
    for index in range(M):
      WX = np.sum(np.multiply(W, X[index, :]))
      linear_sum = WX + b
      y_linear_sum_mult = Y[index] * linear_sum
      y_linear_sum_mult = (1 - y_linear_sum_mult)
      perceptron_loss = float(np.maximum(y_linear_sum_mult, 0) ** 2)
      w1_grad = (2 * np.maximum(0, (y_linear_sum_mult)) * -1 * Y[index] * X[index, 0])
      w2_grad = (2 * np.maximum(0, (y_linear_sum_mult)) * -1 * Y[index] * X[index, 1])
      w3_grad = (2 * np.maximum(0, (y_linear_sum_mult)) * -1 * Y[index] * X[index, 2])
      w4_grad = (2 * np.maximum(0, (y_linear_sum_mult)) * -1 * Y[index] * X[index, 3])
      b_grad = (2 * np.maximum(0, (y_linear_sum_mult)) * -1 * Y[index])
      W[0] = float(float(W[0]) - (float(step_size) * float(w1_grad)))
      W[1] = float(W[1]) - (float(step_size) * float(w2_grad))
      W[2] = float(W[2]) - (float(step_size) * float(w3_grad))
      W[3] = float(W[3]) - (float(step_size) * float(w4_grad))
      b = float(b) - (step_size * b_grad)
      num_epochs += 1
      valid_break = False
      if check_convergence(W, X, b, Y, M):
        print("Converges at:", num_epochs)
        valid_break = True
        break
    if valid_break:
      break

In [34]:
varying_step_sizes_stochastic(step_size=0.01)

Converges at: 97891


In [67]:
varying_step_sizes_stochastic(step_size=0.001)

Converges at: 338036


In [70]:
# *********************************************************

In [36]:
# Problem 2
# Fitting in transformed space with Perceptron Loss

In [37]:
# Problem 2.1.b

In [38]:
M = 2
X = np.array([[1, 1, 1], [1, 1, -1]]).reshape(2, 3)
Y = np.array([1,-1]).reshape(2, 1)
step_size = 0.01
num_epochs = 0
W = np.array([0.0, 0.0, 0.0])
b = 0
while True:
  WX = np.sum(np.multiply(W, X), axis=1)
  linear_sum = WX + b
  y_linear_sum_mult = np.multiply(Y, linear_sum.reshape(-1, 1)) * -1
  perceptron_loss = np.maximum(y_linear_sum_mult, 0)
  perceptron_loss = (1 / M) * np.sum(perceptron_loss)
  w1_grad = 0
  w2_grad = 0
  w3_grad = 0
  b_grad = 0
  for index in range(M):
    if y_linear_sum_mult[index] >= 0:
      w1_grad += (-1 * Y[index] * X[index, 0])
      w2_grad += (-1 * Y[index] * X[index, 1])
      w3_grad += (-1 * Y[index] * X[index, 2])
      b_grad += (-1 * Y[index])
  W[0] = float(W[0]) - (float(step_size) * float(w1_grad))
  W[1] = float(W[1]) - (float(step_size) * float(w2_grad))
  W[2] = float(W[2]) - (float(step_size) * float(w3_grad))
  b = float(b) - (step_size * b_grad)
  num_epochs += 1
  if check_convergence(W, X, b, Y, M):
    print(W, b)
    print("Converges at:", num_epochs)
    break

[0.   0.   0.02] [0.]
Converges at: 1


In [39]:
# Problem 2.1.d

In [40]:
# Modified Standard Gradient Descent
M = 4
X = np.array([[0.8414709848, 1], [0.8414709848, -1], [-0.8414709848, 1], [-0.8414709848, -1]]).reshape(4, 2)
Y = np.array([1,1,-1,-1]).reshape(4, 1)
step_size = 0.01
num_epochs = 0
W = np.array([0.0, 0.0])
b = 0
while True:
  WX = np.sum(np.multiply(W, X), axis=1) # 999 * 1
  linear_sum = WX + b # 999 * 1
  y_linear_sum_mult = np.multiply(Y, linear_sum.reshape(-1, 1)) * -1 # 999 * 1
  perceptron_loss = np.maximum(y_linear_sum_mult, 0) ### 999 * 1
  perceptron_loss = (1 / M) * np.sum(perceptron_loss) # scalar
  w1_grad = 0
  w2_grad = 0
  b_grad = 0
  for index in range(M):
    if y_linear_sum_mult[index] >= 0:
      w1_grad += (-1 * Y[index] * X[index, 0])
      w2_grad += (-1 * Y[index] * X[index, 1])
      b_grad += (-1 * Y[index])
  W[0] = float(float(W[0]) - (float(step_size) * float(w1_grad)))
  W[1] = float(W[1]) - (float(step_size) * float(w2_grad))
  b = float(b) - (step_size * b_grad)
  num_epochs += 1
  if check_convergence(W, X, b, Y, M):
    print(W, b)
    print("Converges at:", num_epochs)
    break

[0.03365884 0.        ] [0.]
Converges at: 1


In [69]:
# *********************************************************

In [42]:
# Problem 3

In [ ]:
## Optimal Weight Computation

In [49]:
mystery_df = pd.read_csv('mystery.data', names=["x1", "x2", "x3", "x4", "y"], header=None)
mystery_df_positive = mystery_df[mystery_df["y"] == 1]
mystery_df_negative = mystery_df[mystery_df["y"] == -1]
X = mystery_df[["x1", "x2", "x3", "x4"]].to_numpy()
Y = mystery_df[["y"]].to_numpy()
n = X.shape[0]
H = np.multiply(np.matmul(Y, Y.T), np.matmul(X, X.T)**3)
q = np.repeat([-1.0], n)
A = Y.reshape(1, -1)
b = 0.0
G = np.negative(np.eye(n))
h = np.zeros(n)
A = A.astype('float')
P = matrix(H)
q = matrix(q)
G = matrix(G)
h = matrix(h)
A = matrix(A)
b = matrix(b)
sol = solvers.qp(P, q, G, h, A, b)
alphas = np.array(sol["x"])
optimal_w = np.dot((Y * alphas).T, X)[0]

     pcost       dcost       gap    pres   dres
 0: -5.4570e+02 -1.3084e+03  6e+03  9e+01  2e+00
 1: -1.7812e+03 -2.6236e+03  4e+03  5e+01  1e+00
 2: -3.6681e+03 -4.1893e+03  4e+03  4e+01  1e+00
 3: -7.6478e+03 -8.2189e+03  4e+03  4e+01  1e+00
 4: -2.6242e+04 -2.6747e+04  6e+03  4e+01  1e+00
 5: -4.9633e+04 -5.0199e+04  7e+03  4e+01  1e+00
 6: -8.1256e+04 -8.1452e+04  1e+04  4e+01  1e+00
 7: -8.9993e+04 -8.9323e+04  2e+04  4e+01  1e+00
 8: -8.3051e+04 -8.0316e+04  3e+04  4e+01  1e+00
 9: -8.1567e+04 -7.6108e+04  3e+04  3e+01  9e-01
10: -6.9998e+04 -6.0536e+04  5e+04  3e+01  9e-01
11: -5.5121e+04 -3.6745e+04  6e+04  2e+01  7e-01
12: -1.9115e+04 -5.1346e+03  4e+04  1e+01  3e-01
13: -1.0371e+03 -3.2249e+01  3e+03  6e-01  2e-02
14: -1.1462e+01 -1.4009e+01  3e+01  5e-03  1e-04
15: -8.2850e+00 -1.0003e+01  3e+00  2e-04  5e-06
16: -9.1810e+00 -9.6968e+00  7e-01  4e-05  1e-06
17: -9.1917e+00 -9.6686e+00  6e-01  3e-05  7e-07
18: -9.5374e+00 -9.6064e+00  9e-02  4e-06  1e-07
19: -9.5950e+00 -9.59

In [50]:
optimal_w

array([-1.86439157, -8.03600773, 16.5629183 , -8.00807034])

In [54]:
## Optimal bias calculation

In [52]:
X_pos = mystery_df_positive[["x1", "x2", "x3", "x4"]].to_numpy()
linear_postive = np.sum(np.multiply(optimal_w, X_pos), axis=1)
X_neg = mystery_df_negative[["x1", "x2", "x3", "x4"]].to_numpy()
linear_negative = np.sum(np.multiply(optimal_w, X_neg), axis=1)

max_index_neg = np.argmax(linear_negative)
min_index_pos = np.argmin(linear_postive)
bias = (linear_postive[min_index_pos] + linear_negative[max_index_neg]) * -1 / 2

In [53]:
bias

-4.047825060327497

In [80]:
print("Optimal Weight:", optimal_w, "Optimal Bias:", bias)

Optimal Weight: [-1.86439157 -8.03600773 16.5629183  -8.00807034] Optimal Bias: -4.047825060327497


In [55]:
## Optimal Margin Computation

In [79]:
w_norm = LA.norm(optimal_w)
optimal_margin = 2 / w_norm
print("Optimal Margin:", optimal_margin)

Optimal Margin: 0.09919570481067863


In [ ]:
### Support Vectors

In [60]:
print("Support Vector For +1 Label:")
print(mystery_df_positive.iloc[min_index_pos, :])
print("******")
print("Support Vector For -1 Label:")
print(mystery_df_negative.iloc[max_index_neg, :])

Support Vector For +1 Label:
x1   -1.714642
x2    4.435944
x3   -4.851051
x4    4.532657
y     1.000000
Name: 403, dtype: float64
******
Support Vector For -1 Label:
x1    1.028716
x2   -4.743268
x3    4.908330
x4   -4.957036
y    -1.000000
Name: 434, dtype: float64


In [71]:
# *********************************************************